/** Exact `<symbol id>` values from `public/sprite.svg`. */
export const ICON_NAMES = [
  "astro",
  "bars",
  "book-open",
  "brain",
  "briefcase",
  "calendar",
  "circle-check",
  "cloudflare",
  "code",
  "css3",
  "database",
  "download",
  "envelope",
  "external-link",
  "fastapi",
  "figma",
  "flame",
  "git",
  "git-branch",
  "github",
  "html5",
  "infinity",
  "layout",
  "linkedin",
  "map-pin",
  "monitor",
  "moon",
  "network",
  "nextjs",
  "node-js",
  "palette",
  "postgresql",
  "python",
  "react",
  "server",
  "settings-2",
  "sparkles",
  "sun",
  "table",
  "tailwind-css",
  "terminal",
  "typescript",
  "whatsapp",
  "wind",
  "xmark",
  "zap",
] as const;

export type IconName = (typeof ICON_NAMES)[number];

/** Friendly aliases for data-driven usage (map → sprite id). */
export const ICON = {
  astro: "astro",
  bars: "bars",
  bookOpen: "book-open",
  brain: "brain",
  briefcase: "briefcase",
  calendar: "calendar",
  circleCheck: "circle-check",
  cloudflare: "cloudflare",
  code: "code",
  css: "css3",
  css3: "css3",
  database: "database",
  download: "download",
  envelope: "envelope",
  externalLink: "external-link",
  fastapi: "fastapi",
  figma: "figma",
  flame: "flame",
  git: "git",
  gitBranch: "git-branch",
  github: "github",
  html: "html5",
  html5: "html5",
  infinity: "infinity",
  layout: "layout",
  linkedin: "linkedin",
  mapPin: "map-pin",
  menu: "bars",
  monitor: "monitor",
  moon: "moon",
  network: "network",
  nextjs: "nextjs",
  node: "node-js",
  nodeJs: "node-js",
  nodejs: "node-js",
  palette: "palette",
  postgres: "postgresql",
  postgresql: "postgresql",
  python: "python",
  react: "react",
  server: "server",
  settings2: "settings-2",
  sparkles: "sparkles",
  sun: "sun",
  table: "table",
  tailwind: "tailwind-css",
  tailwindCss: "tailwind-css",
  terminal: "terminal",
  typescript: "typescript",
  whatsapp: "whatsapp",
  wind: "wind",
  close: "xmark",
  xmark: "xmark",
  zap: "zap",
} as const satisfies Record<string, IconName>;
